### ISSUE TITLE
Error when running "launch xarm_description xarm6_rviz_display.launch.py"

### ISSUE THREAD

**Issue by wxgisu** [xArm-Developer/xarm_ros2#21]
I'm trying to follow the [humble branch readme](https://github.com/xArm-Developer/xarm_ros2/tree/humble#readme) to build and run the xarm application. When executing `ros2 launch xarm_description xarm6_rviz_display.launch.py add_gripper:=true` (in [this step](https://github.com/xArm-Developer/xarm_ros2/tree/humble#51-xarm_description)), I've seen following error: 

```
[INFO] [launch]: All log files can be found below /home/xiaoguang/.ros/log/2022-12-26-12-41-34-380288-xiaoguang-desktop-1729766
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executable '[<launch.substitutions.text_substitution.TextSubstitution object at 0x7f6d80d78e50>]' not found on the PATH
```

I have already run `source ~/dev_ws/install/setup.zsh` in my terminal to ensure env variables are properly set. 

I understand what that error is complaining about. But I don't know  
1) what the `launch.substitutions.text_substitution.TextSubstitution object` is
2) how to add it to PATH

Could someone help shining some lights here? Thanks!

**Comment by penglongxiang** [comment]
Hi @wxgisu, we did not reproduce this issue in humble environment. Have you checked if you have problem running other ROS2 packages or the official tutorials? If the problem persists, maybe you can try re-installing ROS2 environment.

**Comment by wxgisu** [comment]
Hi @penglongxiang, thanks for your response. It turned out that I was using a built from source version of ros2, instead of the binary one installed by apt. Once I switched to the binary one and rebuilt the xarm workspace, things worked. Thanks!
