### ISSUE TITLE
Detecting object in gripper with force feedback

### ISSUE THREAD

**Issue by SyllogismRXS** [xArm-Developer/xarm_ros2#42]
Is there a way to determine if an object is in the xarm gripper's grasp by monitoring the force/current being applied by the gripper's motor? I am picking up objects of various sizes and it would be convenient to just close the gripper until a current spike is detected.

**Comment by penglongxiang** [comment]
Hi, sorry there is no force/current feedback & control for our gripper so far.

**Comment by SyllogismRXS** [comment]
Thanks for response.
