### ISSUE TITLE
I was wondering how can I control the electric sliding rail with ROS2?

### ISSUE THREAD

**Issue by M4D-SC1ENTIST** [xArm-Developer/xarm_ros2#44]
Both in simulation and in real world

**Comment by M4D-SC1ENTIST** [comment]
Got it. Do you have any 3D model of the linear track? I am planning to implement it in Gazebo.

**Comment by MinnaZhong** [comment]
Hi, You can download 3D file of the linear motor from our official website, thank you.
https://www.ufactory.cc/download/
