### ISSUE TITLE
Cannot execute planned moves "Unable to identify any set of controllers that can actuate the specified joints".

### ISSUE THREAD

**Issue by GuiMateus** [xArm-Developer/xarm_ros2#6]
I've been trying to get this driver to run in my machine, however it seems that I am running into some problems with executing planned moves.  I understand that the repo is targeted for Foxy, but I am attempting to run it in Galactic. For reference, the UR driver for ROS2 plans and executes moves correctly, so does the Xarm driver for ROS-Noetic.

In order to get this repo to run for galactic I had modify 

> xarm_controller/include/xar_controller/fake_xarm_hw.h

 and 

> xarm_controller/include/xar_controller/xarm_hw.h

 since some of the functions from hardware_interface don't seem to be virtual in Galactic, causing the building process to fail if not modified.

Screenshots:
Path planning is successful and controller is not found:
![image](https://user-images.githubusercontent.com/43201054/148385060-6276d004-8793-40b2-a9c6-72f4fc37a355.png)
This also caught my attention:
![image](https://user-images.githubusercontent.com/43201054/148385175-58a8f140-65ca-43bb-8d88-d312f8dd0750.png)

System:

- ROS2 Galactic
- Pop!OS 20.04

Full logs:

> [INFO] [launch]: All log files can be found below /home/guilherme/.ros/log/2022-01-06-12-25-18-151700-pop-os-84212
> [INFO] [launch]: Default logging verbosity is set to INFO
> [INFO] [robot_state_publisher-1]: process started with pid [84225]
> [INFO] [rviz2-2]: process started with pid [84227]
> [INFO] [static_transform_publisher-3]: process started with pid [84229]
> [INFO] [move_group-4]: process started with pid [84231]
> [INFO] [joint_state_publisher-5]: process started with pid [84233]
> [INFO] [ros2_control_node-6]: process started with pid [84235]
> [INFO] [spawner.py-7]: process started with pid [84237]
> [static_transform_publisher-3] [INFO] [1641468319.330395189] [static_transform_publisher]: Spinning until killed publishing transform from 'world' to 'link_base'
> [robot_state_publisher-1] Link link_base had 1 children
> [robot_state_publisher-1] Link link1 had 1 children
> [robot_state_publisher-1] Link link2 had 1 children
> [robot_state_publisher-1] Link link3 had 1 children
> [robot_state_publisher-1] Link link4 had 1 children
> [robot_state_publisher-1] Link link5 had 1 children
> [robot_state_publisher-1] Link link6 had 1 children
> [robot_state_publisher-1] Link link_eef had 0 children
> [robot_state_publisher-1] [INFO] [1641468319.333149556] [robot_state_publisher]: got segment link1
> [robot_state_publisher-1] [INFO] [1641468319.333217231] [robot_state_publisher]: got segment link2
> [robot_state_publisher-1] [INFO] [1641468319.333229663] [robot_state_publisher]: got segment link3
> [robot_state_publisher-1] [INFO] [1641468319.333238812] [robot_state_publisher]: got segment link4
> [robot_state_publisher-1] [INFO] [1641468319.333248240] [robot_state_publisher]: got segment link5
> [robot_state_publisher-1] [INFO] [1641468319.333259205] [robot_state_publisher]: got segment link6
> [robot_state_publisher-1] [INFO] [1641468319.333269821] [robot_state_publisher]: got segment link_base
> [robot_state_publisher-1] [INFO] [1641468319.333282043] [robot_state_publisher]: got segment link_eef
> [robot_state_publisher-1] [INFO] [1641468319.333291611] [robot_state_publisher]: got segment world
> [ros2_control_node-6] terminate called after throwing an instance of 'std::runtime_error'
> [ros2_control_node-6]   what():  Wrong state or command interface configuration.
> [ros2_control_node-6] missing state interfaces:
> [ros2_control_node-6] ' joint1/position '	' joint1/velocity '	' joint2/position '	' joint2/velocity '	' joint3/position '	' joint3/velocity '	' joint4/position '	' joint4/velocity '	' joint5/position '	' joint5/velocity '	' joint6/position '	' joint6/velocity '	
> [ros2_control_node-6] missing command interfaces:
> [ros2_control_node-6] ' joint1/position '	' joint1/velocity '	' joint2/position '	' joint2/velocity '	' joint3/position '	' joint3/velocity '	' joint4/position '	' joint4/velocity '	' joint5/position '	' joint5/velocity '	' joint6/position '	' joint6/velocity '	
> [move_group-4] [WARN] [1641468319.360900506] [move_group.move_group]: MoveGroup launched without ~default_planning_pipeline specifying the namespace for the default planning pipeline configuration
> [move_group-4] [WARN] [1641468319.360960569] [move_group.move_group]: Falling back to using the the move_group node namespace (deprecated behavior).
> [move_group-4] [INFO] [1641468319.363261741] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00215583 seconds
> [move_group-4] [INFO] [1641468319.363292750] [moveit_robot_model.robot_model]: Loading robot model 'xarm6'...
> [move_group-4] [INFO] [1641468319.363304623] [moveit_robot_model.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
> [move_group-4] Link link_base had 1 children
> [move_group-4] Link link1 had 1 children
> [move_group-4] Link link2 had 1 children
> [move_group-4] Link link3 had 1 children
> [move_group-4] Link link4 had 1 children
> [move_group-4] Link link5 had 1 children
> [move_group-4] Link link6 had 1 children
> [move_group-4] Link link_eef had 0 children
> [spawner.py-7] [INFO] [1641468319.493458806] [spawner_xarm6_traj_controller]: Waiting for /controller_manager services
> [ERROR] [ros2_control_node-6]: process has died [pid 84235, exit code -6, cmd '/home/guilherme/rosWorkspaces/urdriver/install/controller_manager/lib/controller_manager/ros2_control_node --ros-args --params-file /tmp/launch_params_owlpg5uc --params-file /home/guilherme/rosWorkspaces/xarmdriver_no_update/install/xarm_controller/share/xarm_controller/config/xarm6_controllers.yaml'].
> [move_group-4] [INFO] [1641468319.559645313] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
> [move_group-4] [INFO] [1641468319.559888148] [moveit.ros_planning_interface.moveit_cpp]: Listening to 'joint_states' for joint states
> [move_group-4] [INFO] [1641468319.560327445] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
> [move_group-4] [INFO] [1641468319.560989462] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
> [move_group-4] [INFO] [1641468319.561042471] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
> [move_group-4] [INFO] [1641468319.561814138] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/planning_scene'
> [move_group-4] [INFO] [1641468319.561864073] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
> [move_group-4] [INFO] [1641468319.562328303] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'collision_object'
> [move_group-4] [INFO] [1641468319.562773675] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
> [move_group-4] [WARN] [1641468319.564160287] [moveit.ros.occupancy_map_monitor.middleware_handle]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
> [move_group-4] [ERROR] [1641468319.564187944] [moveit.ros.occupancy_map_monitor.middleware_handle]: No 3D sensor plugin(s) defined for octomap updates
> [move_group-4] [INFO] [1641468319.633759825] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'move_group'
> [move_group-4] [INFO] [1641468319.651469958] [moveit.ros_planning.planning_pipeline]: Using planning interface 'OMPL'
> [move_group-4] [INFO] [1641468319.654657894] [moveit_ros.add_time_optimal_parameterization]: Param 'move_group.path_tolerance' was not set. Using default value: 0.100000
> [move_group-4] [INFO] [1641468319.654687925] [moveit_ros.add_time_optimal_parameterization]: Param 'move_group.resample_dt' was not set. Using default value: 0.100000
> [move_group-4] [INFO] [1641468319.654694071] [moveit_ros.add_time_optimal_parameterization]: Param 'move_group.min_angle_change' was not set. Using default value: 0.001000
> [move_group-4] [INFO] [1641468319.654706153] [moveit_ros.fix_workspace_bounds]: Param 'move_group.default_workspace_bounds' was not set. Using default value: 10.000000
> [move_group-4] [INFO] [1641468319.654719004] [moveit_ros.fix_start_state_bounds]: Param 'move_group.start_state_max_bounds_error' was set to 0.100000
> [move_group-4] [INFO] [1641468319.654725569] [moveit_ros.fix_start_state_bounds]: Param 'move_group.start_state_max_dt' was not set. Using default value: 0.500000
> [move_group-4] [INFO] [1641468319.654734229] [moveit_ros.fix_start_state_collision]: Param 'move_group.start_state_max_dt' was not set. Using default value: 0.500000
> [move_group-4] [INFO] [1641468319.654739537] [moveit_ros.fix_start_state_collision]: Param 'move_group.jiggle_fraction' was not set. Using default value: 0.020000
> [move_group-4] [INFO] [1641468319.654749524] [moveit_ros.fix_start_state_collision]: Param 'move_group.max_sampling_attempts' was not set. Using default value: 100
> [move_group-4] [INFO] [1641468319.654758953] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
> [move_group-4] [INFO] [1641468319.654765238] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
> [move_group-4] [INFO] [1641468319.654769569] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
> [move_group-4] [INFO] [1641468319.654794292] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
> [move_group-4] [INFO] [1641468319.654798692] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
> [joint_state_publisher-5] [INFO] [1641468319.769505013] [joint_state_publisher]: Waiting for robot_description to be published on the robot_description topic...
> [rviz2-2] [INFO] [1641468319.982851566] [rviz2]: Stereo is NOT SUPPORTED
> [rviz2-2] [INFO] [1641468319.983012339] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
> [rviz2-2] [INFO] [1641468320.037965992] [rviz2]: Stereo is NOT SUPPORTED
> [rviz2-2] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occured with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
> [rviz2-2]          at line 253 in /opt/ros/galactic/include/class_loader/class_loader_core.hpp
> [spawner.py-7] [INFO] [1641468321.505413742] [spawner_xarm6_traj_controller]: Waiting for /controller_manager services
> [rviz2-2] [ERROR] [1641468323.167723593] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
> [rviz2-2] [INFO] [1641468323.330952244] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00422018 seconds
> [rviz2-2] [INFO] [1641468323.331029278] [moveit_robot_model.robot_model]: Loading robot model 'xarm6'...
> [rviz2-2] [INFO] [1641468323.331046459] [moveit_robot_model.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
> [rviz2-2] Link link_base had 1 children
> [rviz2-2] Link link1 had 1 children
> [rviz2-2] Link link2 had 1 children
> [rviz2-2] Link link3 had 1 children
> [rviz2-2] Link link4 had 1 children
> [rviz2-2] Link link5 had 1 children
> [rviz2-2] Link link6 had 1 children
> [rviz2-2] Link link_eef had 0 children
> [spawner.py-7] [INFO] [1641468323.518336181] [spawner_xarm6_traj_controller]: Waiting for /controller_manager services
> [rviz2-2] [INFO] [1641468323.530184119] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
> [rviz2-2] [INFO] [1641468323.531197084] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/monitored_planning_scene'
> [rviz2-2] [INFO] [1641468323.538556588] [interactive_marker_display_94322169564912]: Connected on namespace: /rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic
> [rviz2-2] Link link_base had 1 children
> [rviz2-2] Link link1 had 1 children
> [rviz2-2] Link link2 had 1 children
> [rviz2-2] Link link3 had 1 children
> [rviz2-2] Link link4 had 1 children
> [rviz2-2] Link link5 had 1 children
> [rviz2-2] Link link6 had 1 children
> [rviz2-2] Link link_eef had 0 children
> [rviz2-2] [INFO] [1641468323.562813073] [interactive_marker_display_94322169564912]: Sending request for interactive markers
> [rviz2-2] [INFO] [1641468323.593852390] [interactive_marker_display_94322169564912]: Service response received for initialization
> [move_group-4] [WARN] [1641468324.674623921] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Waiting for xarm6_traj_controller/follow_joint_trajectory to come up
> [spawner.py-7] [INFO] [1641468325.532747412] [spawner_xarm6_traj_controller]: Waiting for /controller_manager services
> [spawner.py-7] [INFO] [1641468327.548200736] [spawner_xarm6_traj_controller]: Waiting for /controller_manager services
> [rviz2-2] [INFO] [1641468328.544840129] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Failed to call service get_planning_scene, have you launched move_group or called psm.providePlanningSceneService()?
> [rviz2-2] [INFO] [1641468328.545045879] [moveit_ros_visualization.motion_planning_frame]: group xarm6
> [rviz2-2] [INFO] [1641468328.545066481] [moveit_ros_visualization.motion_planning_frame]: Constructing new MoveGroup connection for group 'xarm6' in namespace ''
> [rviz2-2] [WARN] [1641468328.545599294] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
> [spawner.py-7] [ERROR] [1641468329.561670317] [spawner_xarm6_traj_controller]: Controller manager not available
> [move_group-4] [WARN] [1641468329.674914530] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Waiting for xarm6_traj_controller/follow_joint_trajectory to come up
> [spawner.py-7] /home/guilherme/rosWorkspaces/urdriver/install/controller_manager/lib/controller_manager/spawner.py:204: DeprecationWarning: 'spawner.py' is deprecated, please use 'spawner' (without .py extension)
> [spawner.py-7]   warnings.warn(
> [ERROR] [spawner.py-7]: process has died [pid 84237, exit code 1, cmd '/home/guilherme/rosWorkspaces/urdriver/install/controller_manager/lib/controller_manager/spawner.py xarm6_traj_controller --controller-manager /controller_manager --ros-args'].
> [move_group-4] [ERROR] [1641468334.675433194] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Action client not connected: xarm6_traj_controller/follow_joint_trajectory
> [move_group-4] [INFO] [1641468334.682923509] [moveit.plugins.moveit_simple_controller_manager]: Returned 0 controllers in list
> [move_group-4] [INFO] [1641468334.683407223] [moveit_ros.trajectory_execution_manager]: Trajectory execution is managing controllers
> [move_group-4] [INFO] [1641468334.683435229] [move_group.move_group]: MoveGroup debug mode is ON
> [move_group-4] [INFO] [1641468334.702659433] [move_group.move_group]: 
> [move_group-4] 
> [move_group-4] ********************************************************
> [move_group-4] * MoveGroup using: 
> [move_group-4] *     - ApplyPlanningSceneService
> [move_group-4] *     - ClearOctomapService
> [move_group-4] *     - CartesianPathService
> [move_group-4] *     - ExecuteTrajectoryAction
> [move_group-4] *     - GetPlanningSceneService
> [move_group-4] *     - KinematicsService
> [move_group-4] *     - MoveAction
> [move_group-4] *     - MotionPlanService
> [move_group-4] *     - QueryPlannersService
> [move_group-4] *     - StateValidationService
> [move_group-4] ********************************************************
> [move_group-4] 
> [move_group-4] [INFO] [1641468334.702704131] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
> [move_group-4] [INFO] [1641468334.702713699] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context initialization complete
> [move_group-4] Loading 'move_group/ApplyPlanningSceneService'...
> [move_group-4] Loading 'move_group/ClearOctomapService'...
> [move_group-4] Loading 'move_group/MoveGroupCartesianPathService'...
> [move_group-4] Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
> [move_group-4] Loading 'move_group/MoveGroupGetPlanningSceneService'...
> [move_group-4] Loading 'move_group/MoveGroupKinematicsService'...
> [move_group-4] Loading 'move_group/MoveGroupMoveAction'...
> [move_group-4] Loading 'move_group/MoveGroupPlanService'...
> [move_group-4] Loading 'move_group/MoveGroupQueryPlannersService'...
> [move_group-4] Loading 'move_group/MoveGroupStateValidationService'...
> [move_group-4] 
> [move_group-4] You can start planning now!
> [move_group-4] 
> [rviz2-2] [INFO] [1641468334.705313858] [move_group_interface]: Ready to take commands for planning group xarm6.
> [rviz2-2] [INFO] [1641468334.705366448] [move_group_interface]: Looking around: no
> [rviz2-2] [INFO] [1641468334.705380835] [move_group_interface]: Replanning: no
> [rviz2-2] [INFO] [1641468334.706266481] [moveit_ros_visualization.motion_planning_frame]: group xarm6
> [rviz2-2] [INFO] [1641468334.706348334] [moveit_ros_visualization.motion_planning_frame]: group xarm6
> [rviz2-2] [INFO] [1641468334.744528974] [moveit_ros_visualization.motion_planning_frame_planning]: POPULATING PLANNERS 24 grp: xarm6
> [rviz2-2] [INFO] [1641468334.744657830] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6
> [rviz2-2] [INFO] [1641468334.744665582] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[BFMT]
> [rviz2-2] [INFO] [1641468334.744723479] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[BKPIECE]
> [rviz2-2] [INFO] [1641468334.744730254] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[BiEST]
> [rviz2-2] [INFO] [1641468334.744735422] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[BiTRRT]
> [rviz2-2] [INFO] [1641468334.744739682] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[EST]
> [rviz2-2] [INFO] [1641468334.744744432] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[FMT]
> [rviz2-2] [INFO] [1641468334.744749670] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[KPIECE]
> [rviz2-2] [INFO] [1641468334.744754419] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[LBKPIECE]
> [rviz2-2] [INFO] [1641468334.744758819] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[LBTRRT]
> [rviz2-2] [INFO] [1641468334.744763568] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[LazyPRM]
> [rviz2-2] [INFO] [1641468334.744768317] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[LazyPRMstar]
> [rviz2-2] [INFO] [1641468334.744773136] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[PDST]
> [rviz2-2] [INFO] [1641468334.744802190] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[PRM]
> [rviz2-2] [INFO] [1641468334.744807428] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[PRMstar]
> [rviz2-2] [INFO] [1641468334.744812596] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[ProjEST]
> [rviz2-2] [INFO] [1641468334.744816926] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[RRTConnect]
> [rviz2-2] [INFO] [1641468334.744821745] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[RRT]
> [rviz2-2] [INFO] [1641468334.744826564] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[RRTstar]
> [rviz2-2] [INFO] [1641468334.744831313] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[SBL]
> [rviz2-2] [INFO] [1641468334.744835992] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[SPARS]
> [rviz2-2] [INFO] [1641468334.744840811] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[SPARStwo]
> [rviz2-2] [INFO] [1641468334.744845980] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[STRIDE]
> [rviz2-2] [INFO] [1641468334.744850310] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: xarm6[TRRT]
> [move_group-4] [INFO] [1641468947.613554962] [moveit_move_group_default_capabilities.move_action_capability]: Received request
> [move_group-4] [INFO] [1641468947.613848222] [moveit_move_group_default_capabilities.move_action_capability]: executing..
> [move_group-4] [INFO] [1641468947.675595206] [moveit_move_group_default_capabilities.move_action_capability]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
> [move_group-4] [INFO] [1641468947.675929811] [moveit_move_group_capabilities_base.move_group_capability]: Using planning pipeline 'move_group'
> [move_group-4] [INFO] [1641468947.677310138] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'xarm6' will use planner 'geometric::RRT'. Additional configuration parameters will be set when the planner is constructed.
> [move_group-4] [INFO] [1641468947.678476892] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:119 - xarm6/xarm6: Starting planning with 1 states already in datastructure
> [move_group-4] [INFO] [1641468947.678558466] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:119 - xarm6/xarm6: Starting planning with 1 states already in datastructure
> [move_group-4] [INFO] [1641468947.678613779] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:119 - xarm6/xarm6: Starting planning with 1 states already in datastructure
> [move_group-4] [INFO] [1641468947.678666788] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:119 - xarm6/xarm6: Starting planning with 1 states already in datastructure
> [move_group-4] [INFO] [1641468947.687758478] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:227 - xarm6/xarm6: Created 75 states
> [move_group-4] [INFO] [1641468947.688499066] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:227 - xarm6/xarm6: Created 76 states
> [move_group-4] [INFO] [1641468947.688931727] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:227 - xarm6/xarm6: Created 78 states
> [move_group-4] [INFO] [1641468947.691287585] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:227 - xarm6/xarm6: Created 136 states
> [move_group-4] [INFO] [1641468947.691428174] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/tools/multiplan/src/ParallelPlan.cpp:135 - ParallelPlan::solve(): Solution found by one or more threads in 0.013685 seconds
> [move_group-4] [INFO] [1641468947.691653619] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:119 - xarm6/xarm6: Starting planning with 1 states already in datastructure
> [move_group-4] [INFO] [1641468947.691688050] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:119 - xarm6/xarm6: Starting planning with 1 states already in datastructure
> [move_group-4] [INFO] [1641468947.691707396] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:119 - xarm6/xarm6: Starting planning with 1 states already in datastructure
> [move_group-4] [INFO] [1641468947.691736100] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:119 - xarm6/xarm6: Starting planning with 1 states already in datastructure
> [move_group-4] [INFO] [1641468947.692524878] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:227 - xarm6/xarm6: Created 12 states
> [move_group-4] [INFO] [1641468947.693487768] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:227 - xarm6/xarm6: Created 20 states
> [move_group-4] [INFO] [1641468947.693704553] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:227 - xarm6/xarm6: Created 32 states
> [move_group-4] [INFO] [1641468947.694120383] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:227 - xarm6/xarm6: Created 38 states
> [move_group-4] [INFO] [1641468947.694205449] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/tools/multiplan/src/ParallelPlan.cpp:135 - ParallelPlan::solve(): Solution found by one or more threads in 0.002622 seconds
> [move_group-4] [INFO] [1641468947.694406310] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:119 - xarm6/xarm6: Starting planning with 1 states already in datastructure
> [move_group-4] [INFO] [1641468947.694446957] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:119 - xarm6/xarm6: Starting planning with 1 states already in datastructure
> [move_group-4] [INFO] [1641468947.695154650] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:227 - xarm6/xarm6: Created 11 states
> [move_group-4] [INFO] [1641468947.697715490] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/planners/rrt/src/RRT.cpp:227 - xarm6/xarm6: Created 44 states
> [move_group-4] [INFO] [1641468947.697895119] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/tools/multiplan/src/ParallelPlan.cpp:135 - ParallelPlan::solve(): Solution found by one or more threads in 0.003590 seconds
> [move_group-4] [INFO] [1641468947.697998693] [ompl]: /tmp/binarydeb/ros-galactic-ompl-1.5.2/src/ompl/geometric/src/SimpleSetup.cpp:179 - SimpleSetup: Path simplification took 0.000012 seconds and changed from 2 to 2 states
> [move_group-4] [INFO] [1641468947.699620877] [moveit_move_group_default_capabilities.move_action_capability]: Motion plan was computed succesfully.
> [rviz2-2] [INFO] [1641468948.014958580] [move_group_interface]: Planning request accepted
> [rviz2-2] [INFO] [1641468948.115675622] [move_group_interface]: Planning request complete!
> [rviz2-2] [INFO] [1641468948.216007914] [move_group_interface]: time taken to generate plan: 0.0202975 seconds
> [move_group-4] [INFO] [1641468949.662149136] [moveit_move_group_default_capabilities.execute_trajectory_action_capability]: Received goal request
> [move_group-4] [INFO] [1641468949.662769459] [moveit_move_group_default_capabilities.execute_trajectory_action_capability]: Execution request received
> [move_group-4] [INFO] [1641468949.662905438] [moveit.plugins.moveit_simple_controller_manager]: Returned 0 controllers in list
> [move_group-4] [INFO] [1641468949.662986453] [moveit.plugins.moveit_simple_controller_manager]: Returned 0 controllers in list
> [move_group-4] [ERROR] [1641468949.663023468] [moveit_ros.trajectory_execution_manager]: Unable to identify any set of controllers that can actuate the specified joints: [ joint1 joint2 joint3 joint4 joint5 joint6 ]
> [move_group-4] [ERROR] [1641468949.663051125] [moveit_ros.trajectory_execution_manager]: Known controllers and their joints:
> [move_group-4] 
> [rviz2-2] [INFO] [1641468950.063991212] [move_group_interface]: Execute request accepted
> [rviz2-2] [INFO] [1641468950.164584847] [move_group_interface]: Execute request aborted
> [rviz2-2] [ERROR] [1641468950.264831095] [move_group_interface]: MoveGroupInterface::execute() failed or timeout reached
>

**Comment by MinnaZhong** [comment]
Hi GuiMateus,

Sorry, Galatic is not compatible yet, will let you know once it is supported.

**Comment by vimior** [comment]
Hi @GuiMateus 

Now it is preliminarily compatible with the ROS2 Galactic version. Please switch to the galactic branch. If you have any questions during the use process, please contact us. Thank you for your support.

**Comment by GuiMateus** [comment]
> Hi @GuiMateus
> 
> Now it is preliminarily compatible with the ROS2 Galactic version. Please switch to the galactic branch. If you have any questions during the use process, please contact us. Thank you for your support.

Works perfectly now, thanks :)
