### ISSUE TITLE
why using radian instead of degree by default in service named MoveCartesian

### ISSUE THREAD

**Issue by celaraze** [xArm-Developer/xarm_ros2#65]
Such inconsistent development specifications can easily cause confusion and are not friendly to the developer's experience.

In ROS2, is it more intuitive to use degree instead? Or is there another reason?

### example command

```shell
# x: -297.7
# y: 193
# z: 5002
# r: 3.14 (radian)
# p: 0.1 (radian)
# y: 0.2 (radian)
ros2 service call /xarm/set_position xarm_msgs/srv/MoveCartesian "{pose: [-297.7, 193, 500.2, 3.14, 0.1, 0.2], speed: 50, acc: 500, mvtime: 0}
```

### in UFACTORY Studio

x, y, z postions and r, p, y degrees.

![image](https://github.com/xArm-Developer/xarm_ros2/assets/31471452/468c9946-3494-462e-acc2-ddd15201f7ec)

### in xARM Python SDK

the function named `set_position()` only need x, y, z.

**Comment by penglongxiang** [comment]
Hi @celaraze, since ROS is mainly for developers, it will be convenient to use radian data for trigonometric and other calculations like rotation matrix, Euler angle to Quaternions etc. Most of the available math library functions require radian expression as input, this is the major reason.

**Comment by celaraze** [comment]
> Hi @celaraze, Ufactory Studio is mainly for display, jogging and simple programming, so it will be more important to be intuitive. ROS is targeted for developers, it will be more convenient to use radian data for trigonometric and other calculations like rotation matrix, Euler angles to Quaternions etc. Most of the available math library functions require radian expression as input, this is the major reason.
> 
> Sorry for the inconvenience, you can do a unit transfer or use Python API `get_position(is_radian=True)` to get the robot position in radian.

Thanks, I understand.
