### ISSUE TITLE
isaac_ros_cumotion

### ISSUE THREAD

**Issue by Murali25111993** [xArm-Developer/xarm_ros2#91]
Hello,

I am using xarm6 robot. I am trying in isaac_ros_cumotion. Completed all installation setup. Now in the implementation stage. As per this [link](https://nvidia-isaac-ros.github.io/repositories_and_packages/isaac_ros_cumotion/isaac_ros_cumotion_moveit/index.html), How to setup moveit2 with cumotion for **Another Robot** tab. 
![image](https://github.com/user-attachments/assets/20afa8ac-88cb-4366-a4aa-fac32865e440)

Kindly guide me ,where to add the parameter in the launch file. It will be grateful, if you pointed me to the right launch file.

**Comment by vimior** [comment]
@Murali25111993 
We have not used issa_ros_cumotion either. After you install the support for issa_ros_cumotion, you can try the following operations to see if it works.
1. Copy __issa_ros_cumotion_planning.yaml__ to the `xarm_moveit_config/config/{robot}/` directory
2. Recompile
3. Start the __MotionPlanning__ window in the rviz interface to see if you can switch to `issa_ros_cumotion`

**Comment by Murali25111993** [comment]
Completed thanks. 

Kindly consider adding xrdf file for all the robots along with urdf file. As I made with limited knowledge. Your expertise will have an additional advantage for the xarm users with nvidia isaac_ros. 

This issue can be closed.

**Comment by nehagarg** [comment]
Hi @Murali25111993 ,

Is it possible for you to share your xrdf file for xarm6?
